collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3661888
  brandStrength: 0.2252088231034577
  lightness: 0.6851851
  brandColors:
    - '#8DB1E3'
    - '#DBD7D4'
    - '#32404B'
    - '#087F9D'
    - '#4B9199'
  rhythmicContrast: 0.5955794
typography_spectrum: 0.4926353869959712
layout_spectrum: 0.3861066538374871
name: Testingjens
